datasets:
  0304_실증과제_dataset_train/0304_tape:
    dataset_name: 0304_실증과제_dataset_train/0304_tape
    dataset_dir: /home/dam/igris_teleop_v4/igris_artifacts/datasets/0304_실증과제_dataset_train/0304_tape
    feature: action
    stat: mean
    episodes: 10
    feature_dim: 28
    rows_loaded: 3955
    joint_names:
    - hand_0
    - hand_1
    - hand_2
    - hand_3
    - hand_4
    - hand_5
    - hand_6
    - hand_7
    - hand_8
    - hand_9
    - hand_10
    - hand_11
    - l_shoulder_pitch
    - l_shoulder_roll
    - l_shoulder_yaw
    - l_elbow_pitch
    - l_wrist_yaw
    - l_wrist_roll
    - l_wrist_pitch
    - r_shoulder_pitch
    - r_shoulder_roll
    - r_shoulder_yaw
    - r_elbow_pitch
    - r_wrist_yaw
    - r_wrist_roll
    - r_wrist_pitch
    - neck_yaw
    - neck_pitch
    joint_values:
    - 0.493078196
    - 0.903091891
    - 0.792252673
    - 0.868685025
    - 0.927430652
    - 0.870350281
    - 0.506126074
    - 0.099930601
    - 0.053652133
    - 0.031617843
    - 0.08470755
    - 0.239640715
    - 0.101242746
    - 0.461114689
    - -0.095106822
    - -1.441328548
    - -0.693973004
    - 0.32213601
    - -0.221123361
    - -0.505753536
    - -1.374753772
    - 0.212456368
    - -1.706093668
    - 0.252186476
    - 0.137943241
    - -0.211804427
    - -0.13816621
    - 0.378764347
  0304_실증과제_dataset_train/0304_lifting:
    dataset_name: 0304_실증과제_dataset_train/0304_lifting
    dataset_dir: /home/dam/igris_teleop_v4/igris_artifacts/datasets/0304_실증과제_dataset_train/0304_lifting
    feature: action
    stat: mean
    episodes: 21
    feature_dim: 28
    rows_loaded: 7921
    joint_names:
    - hand_0
    - hand_1
    - hand_2
    - hand_3
    - hand_4
    - hand_5
    - hand_6
    - hand_7
    - hand_8
    - hand_9
    - hand_10
    - hand_11
    - l_shoulder_pitch
    - l_shoulder_roll
    - l_shoulder_yaw
    - l_elbow_pitch
    - l_wrist_yaw
    - l_wrist_roll
    - l_wrist_pitch
    - r_shoulder_pitch
    - r_shoulder_roll
    - r_shoulder_yaw
    - r_elbow_pitch
    - r_wrist_yaw
    - r_wrist_roll
    - r_wrist_pitch
    - neck_yaw
    - neck_pitch
    joint_values:
    - 0.278330157
    - 0.17905162
    - 0.197586296
    - 0.167533677
    - 0.183842208
    - 0.028883507
    - 0.153406359
    - 0.112939477
    - 0.115978518
    - 0.10957603
    - 0.136868876
    - 0.003401367
    - 0.165158621
    - 0.235356513
    - 0.366183179
    - -1.408267605
    - 0.318995001
    - -0.482217884
    - -0.314246965
    - 0.136012982
    - -0.370492935
    - -0.208694463
    - -1.384016096
    - -0.295985286
    - 0.176407815
    - -0.283567345
    - 0.091143754
    - 0.385850811
  0304_실증과제_dataset_train/0304_throwing:
    dataset_name: 0304_실증과제_dataset_train/0304_throwing
    dataset_dir: /home/dam/igris_teleop_v4/igris_artifacts/datasets/0304_실증과제_dataset_train/0304_throwing
    feature: action
    stat: mean
    episodes: 11
    feature_dim: 28
    rows_loaded: 4451
    joint_names:
    - hand_0
    - hand_1
    - hand_2
    - hand_3
    - hand_4
    - hand_5
    - hand_6
    - hand_7
    - hand_8
    - hand_9
    - hand_10
    - hand_11
    - l_shoulder_pitch
    - l_shoulder_roll
    - l_shoulder_yaw
    - l_elbow_pitch
    - l_wrist_yaw
    - l_wrist_roll
    - l_wrist_pitch
    - r_shoulder_pitch
    - r_shoulder_roll
    - r_shoulder_yaw
    - r_elbow_pitch
    - r_wrist_yaw
    - r_wrist_roll
    - r_wrist_pitch
    - neck_yaw
    - neck_pitch
    joint_values:
    - 0.313448382
    - 0.186589193
    - 0.18901309
    - 0.151799476
    - 0.175260332
    - 0.030908622
    - 0.128139522
    - 0.120382157
    - 0.089748933
    - 0.062864135
    - 0.099890794
    - 0.00388044
    - 0.165391042
    - 0.231631131
    - 0.429654133
    - -1.453377271
    - 0.302054804
    - -0.412815205
    - -0.317429477
    - 0.127878234
    - -0.358533196
    - -0.27514041
    - -1.434272235
    - -0.338870348
    - 0.118604622
    - -0.280509344
    - 0.071835934
    - 0.352193091
  0304_실증과제_dataset_train/0304_padding:
    dataset_name: 0304_실증과제_dataset_train/0304_padding
    dataset_dir: /home/dam/igris_teleop_v4/igris_artifacts/datasets/0304_실증과제_dataset_train/0304_padding
    feature: action
    stat: mean
    episodes: 20
    feature_dim: 28
    rows_loaded: 10362
    joint_names:
    - hand_0
    - hand_1
    - hand_2
    - hand_3
    - hand_4
    - hand_5
    - hand_6
    - hand_7
    - hand_8
    - hand_9
    - hand_10
    - hand_11
    - l_shoulder_pitch
    - l_shoulder_roll
    - l_shoulder_yaw
    - l_elbow_pitch
    - l_wrist_yaw
    - l_wrist_roll
    - l_wrist_pitch
    - r_shoulder_pitch
    - r_shoulder_roll
    - r_shoulder_yaw
    - r_elbow_pitch
    - r_wrist_yaw
    - r_wrist_roll
    - r_wrist_pitch
    - neck_yaw
    - neck_pitch
    joint_values:
    - 0.295702942
    - 0.232775713
    - 0.199739979
    - 0.155464112
    - 0.122914442
    - 0.205928796
    - 0.22238235
    - 0.16849463
    - 0.125406892
    - 0.103382463
    - 0.127306988
    - 0.023251383
    - 0.099478668
    - 0.346679706
    - 0.350974853
    - -1.419009124
    - 0.320678728
    - -0.367580197
    - -0.308215132
    - 0.073400991
    - -0.424299145
    - -0.240374823
    - -1.398837274
    - -0.347216599
    - 0.122584257
    - -0.263058567
    - 0.01990547
    - 0.258628337
