from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument('device', default_value='0'),
        DeclareLaunchArgument('camera_retry_interval_s', default_value='1.0'),
        DeclareLaunchArgument('target_hand', default_value='Right'),
        DeclareLaunchArgument('hand_assignment_mode', default_value='target_best'),
        DeclareLaunchArgument('model_complexity', default_value='1'),
        DeclareLaunchArgument('max_hands', default_value='1'),
        DeclareLaunchArgument('publish_inactive_tracked', default_value='false'),
        DeclareLaunchArgument('mirror', default_value='false'),
        DeclareLaunchArgument('swap_lr', default_value='false'),
        DeclareLaunchArgument('trapezoid_preprocess', default_value='true'),
        DeclareLaunchArgument('trapezoid_bottom_width', default_value='320'),
        DeclareLaunchArgument('trapezoid_canvas_width', default_value='1280'),
        DeclareLaunchArgument('trapezoid_canvas_height', default_value='720'),
        DeclareLaunchArgument('trapezoid_display_scale', default_value='1.5'),
        DeclareLaunchArgument('show_image', default_value='true'),
        DeclareLaunchArgument('draw_landmarks', default_value='true'),
        DeclareLaunchArgument('show_assignment_debug', default_value='true'),
        DeclareLaunchArgument('window_name', default_value=''),
        DeclareLaunchArgument('publish_rate_hz', default_value='30.0'),
        DeclareLaunchArgument('coordinate_scale', default_value='1.0'),
        DeclareLaunchArgument('publish_all_landmarks', default_value='true'),
        DeclareLaunchArgument('right_pose_topic', default_value='/right_mediapipe_hand/poses'),
        DeclareLaunchArgument('right_all_pose_topic', default_value='/right_mediapipe_hand/all_poses'),
        DeclareLaunchArgument('right_tracked_topic', default_value='/right_mediapipe_hand/is_tracked'),
        DeclareLaunchArgument('left_pose_topic', default_value='/left_mediapipe_hand/poses'),
        DeclareLaunchArgument('left_all_pose_topic', default_value='/left_mediapipe_hand/all_poses'),
        DeclareLaunchArgument('left_tracked_topic', default_value='/left_mediapipe_hand/is_tracked'),
        Node(
            package='mediapipe_hand_pose_bridge',
            executable='mediapipe_hand_pose_publisher',
            name='mediapipe_hand_pose_publisher',
            output='screen',
            parameters=[{
                'device': ParameterValue(LaunchConfiguration('device'), value_type=str),
                'camera_retry_interval_s': ParameterValue(LaunchConfiguration('camera_retry_interval_s'), value_type=float),
                'target_hand': LaunchConfiguration('target_hand'),
                'hand_assignment_mode': LaunchConfiguration('hand_assignment_mode'),
                'model_complexity': ParameterValue(LaunchConfiguration('model_complexity'), value_type=int),
                'max_hands': ParameterValue(LaunchConfiguration('max_hands'), value_type=int),
                'publish_inactive_tracked': ParameterValue(LaunchConfiguration('publish_inactive_tracked'), value_type=bool),
                'mirror': ParameterValue(LaunchConfiguration('mirror'), value_type=bool),
                'swap_lr': ParameterValue(LaunchConfiguration('swap_lr'), value_type=bool),
                'trapezoid_preprocess': ParameterValue(LaunchConfiguration('trapezoid_preprocess'), value_type=bool),
                'trapezoid_bottom_width': ParameterValue(LaunchConfiguration('trapezoid_bottom_width'), value_type=int),
                'trapezoid_canvas_width': ParameterValue(LaunchConfiguration('trapezoid_canvas_width'), value_type=int),
                'trapezoid_canvas_height': ParameterValue(LaunchConfiguration('trapezoid_canvas_height'), value_type=int),
                'trapezoid_display_scale': ParameterValue(LaunchConfiguration('trapezoid_display_scale'), value_type=float),
                'show_image': ParameterValue(LaunchConfiguration('show_image'), value_type=bool),
                'draw_landmarks': ParameterValue(LaunchConfiguration('draw_landmarks'), value_type=bool),
                'show_assignment_debug': ParameterValue(LaunchConfiguration('show_assignment_debug'), value_type=bool),
                'window_name': LaunchConfiguration('window_name'),
                'publish_rate_hz': ParameterValue(LaunchConfiguration('publish_rate_hz'), value_type=float),
                'coordinate_scale': ParameterValue(LaunchConfiguration('coordinate_scale'), value_type=float),
                'publish_all_landmarks': ParameterValue(LaunchConfiguration('publish_all_landmarks'), value_type=bool),
                'right_pose_topic': LaunchConfiguration('right_pose_topic'),
                'right_all_pose_topic': LaunchConfiguration('right_all_pose_topic'),
                'right_tracked_topic': LaunchConfiguration('right_tracked_topic'),
                'left_pose_topic': LaunchConfiguration('left_pose_topic'),
                'left_all_pose_topic': LaunchConfiguration('left_all_pose_topic'),
                'left_tracked_topic': LaunchConfiguration('left_tracked_topic'),
            }],
        ),
    ])
