from __future__ import annotations


HAND_ACTUATOR_TORQUE_LIMIT_NM = 15.0
HAND_SERVO_KP = 30.0
HAND_SERVO_KD = 1.2
HAND_NEAR_OBJECT_CLOSING_TORQUE_LIMIT = 2.8
HAND_NEAR_OBJECT_OPENING_BRAKE_LIMIT = 1.0
